apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-friendly
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: ui-friendly
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-friendly
    spec:
      containers:
        - name: ui-friendly
          image: sayze/friendly-ui
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.port}}
          env:
            - name: PORT
              value: "{{.Values.port}}"