name: "Release"
on: 
  workflow_run:
    workflows: ["Build and publish"]
    branches: [master]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Upgrade helm chart
        uses: koslibpro/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          command: helm upgrade --install ui-friendly charts -n friendly --set image.tag=${{ github.sha }} --wait